my_venv/myproject/gourmet/urls.py
from django.urls import path
from . import views


app_name = 'gourmet'
urlpatterns = [
    path('',views.TopView.as_view(), name='top'),
    path('detail/<int:pk>',views.StoreDetailView.as_view(),name='detail'),
    path('profile/',views.ProFileView.as_view(),name='profile'),
    path('profile-update/<int:pk>',views.ProfileUpdateView.as_view(),name='profile_update'),
    path('reservation-mail/',views.ReservationMail.as_view(),name='reservation_mail'),
    path('reservation-success/<int:reservation_id>', views.reservation_success, name='reservation_success'),
    path('reserve-list/',views.ReserveListView.as_view(), name='reserve_list'),
    path('reserve-delete/<int:pk>',views.ReserveDeleteView.as_view(),name='reserve_delete'),
    path('review/<int:store_id>/',views.submit_review,name='review_form'),
    path('review-edit/<int:pk>/',views.ReviewUpdateView.as_view(),name='review_edit'),
    path('review-delete/<int:pk>/',views.ReviewDeleteView.as_view(),name='review_delete'),
    path('confirm/',views.ConfirmReservation.as_view(),name='confirm'),
    path('like/<int:store_id>',views.toggle_favorite,name='toggle_favorite'), #like_rest(同期処理)からtoggle_favoriteb (非同期処理)に変更
    path('like-list/',views.LikeListView.as_view(),name='like_list'),
    path('toggle-fav/<int:store_id>/', views.toggle_fav,name ='toggle-fav'),
    path('search/',views.SearchResultView.as_view(),name='search'),
    path('member/',views.MemberShipView.as_view(),name='membership'),
    path('only-member/',views.MemberPageView.as_view(),name='membership_page'),
    path('member-update/<int:pk>/',views.MemberUpdateView.as_view(),name='membership_edit'),
    path('membership-delete/<int:pk>/',views.MembershipDeleteView.as_view(),name='membership_delete'),
    path('mypage/',views.MypageListView.as_view(),name='mypage'),
    path('mypage-form/',views.MyPageFormView.as_view(),name='mypage_form'),
    path('mypage-edit/<int:pk>',views.MypageUpdateView.as_view(),name='mypage_edit'),
    path('mypage-delete/<int:pk>',views.MypageDeleteView.as_view(),name='mypage_delete'),
    path('ourpage/',views.OurpageListView.as_view(),name='ourpage'),
    path('want-list/',views.WantView.as_view(),name='want_list'),
    path('want-list-form/',views.WantFormView.as_view(),name='want_list_form'),
    path('want-list-edit/<int:pk>/',views.WantUpdateView.as_view(),name='want_edit'),
    path('want-list-delete/<int:pk>/',views.WantDeleteView.as_view(),name='want_delete'),
]

my_venv/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from .import settings
from . import settings_common, settings_dev


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gourmet.urls')),
    path('accounts/',include('allauth.urls')),
    path('payment/',include('payment.urls'),)
]

#開発サーバーでメディアを配信できるようにする設定

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

my_venv/myproject/payment/urls.py
from django.urls import path
from . import views
from .views import stripe_webhook


app_name = 'payment'
urlpatterns = [
    path('',views.PaymentIndexView.as_view(),name='index'),
    path('create_checkout_session/', views.create_checkout_session, name='checkout_session'),
    path('success/', views.PaymentSuccessView.as_view(), name='success'),
    path('cancel/', views.PaymentCancelView.as_view(), name='cancel'),
    path('webhook/', stripe_webhook, name='webhook'),
]

my_venv/myproject/payment/models.py
from django.db import models

# Create your models here.

my_venv/myproject/payment/views.py
from django.shortcuts import render
from django.views import generic
import os
import stripe
import json
from django.urls import reverse
from django.shortcuts import redirect
from django.http import JsonResponse
from django.http.response import JsonResponse, HttpResponse 
from django.utils.decorators import method_decorator
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import get_user_model
from gourmet.models import Stripe_Customer

#stripe決済について参考にしたサイト
#https://note.com/daikinishimatsu/n/n029a7ff01f62



class PaymentIndexView(generic.TemplateView):
    template_name = 'payment_index.html'

    def get_context_data(self, **kwargs):
        stripe.api_key = settings.STRIPE_SECRET_KEY
        print("ログインユーザーID",self.request.user.id)
        customer = Stripe_Customer.objects.filter(user__id = self.request.user.id).first()
        if customer is None:
            return {}
        
        print(f'{customer}'"←現在のログインユーザー")
        client_reference_id=self.request.user.id
        print(f'{client_reference_id}'"←現在のログインID")
        print(customer.stripeSubscriptionId,"サブスクの会員ID")
        subscription = stripe.Subscription.retrieve(customer.stripeSubscriptionId)
        print("サブスクリプションのjsonデータ")
        print(subscription)
        product = stripe.Product.retrieve(subscription.plan.product)
        print("activeかどうかを判定",product)

        #htmlに表示
        context = {
            "subscription": subscription,
            "product": product,
        }
        return context

class PaymentSuccessView(generic.TemplateView):
   template_name = "payment_success.html"

class PaymentCancelView(generic.TemplateView):
   template_name = "payment_cancel.html"

def create_checkout_session(request):
   stripe.api_key = 'sk_test_51Q11x3RwNoxwqPY3wi1UPQQlwb0ZYhxsVPwrsIx0p81p0C7g4tcN3rTzxz7RHcuLpRt4ZX1XM2xltTIionkPNHag00b910fCNA'

   try:
       checkout_session = stripe.checkout.Session.create(
           payment_method_types=['card'], #クレカ決済
           line_items=[
                {
                    # Stripeダッシュボードで作成したサブスクリプション用の価格ID
                    'price': 'price_1Q2G28RwNoxwqPY3KG9n4wze',  
                    'quantity': 1,
                },
            ],
           mode='subscription', #月額払いに
           success_url=request.build_absolute_uri(reverse('payment:success')),
           cancel_url=request.build_absolute_uri(reverse('payment:cancel')),
           client_reference_id=request.user.id if request.user.is_authenticated else None, # ここでクライアントリファレンスIDを設定
       )
       return JsonResponse({'id': checkout_session.id})
   except Exception as e:
       print("失敗")
       return JsonResponse({'error':str(e)})    
   
#DjangoでWebhookを受け取るためのビュー
@csrf_exempt
def stripe_webhook(request):
    print("stripe_webhookが呼ばれた！")
    stripe.api_key = settings.STRIPE_SECRET_KEY
    endpoint_secret = settings.STRIPE_ENDPOINT_SECRET
    payload = request.body.decode('utf-8')
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, endpoint_secret
        )
    except ValueError as e:
        # Invalid payload
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':

    #jsondataをフォルダ内に書き込みするテスト  ※webhook使用時   
    # if event['type'] == 'invoice.created':
        # with open("request.json", mode='w') as f:
        #     f.write(str(event))

        session = event['data']['object']

        # Fetch all the required data from session
        client_reference_id = session.get('client_reference_id')
        stripe_customer_id = session.get('customer')
        stripe_subscription_id = session.get('subscription')
        print(client_reference_id)
        print(stripe_customer_id)
        print(stripe_subscription_id)
        # Get the user and create a new Stripe_Customer
 
        user = get_user_model().objects.get(id=client_reference_id)
        print(client_reference_id)
        print(user)
        Stripe_Customer.objects.create(
            user=user,
            stripeCustomerId=stripe_customer_id,
            stripeSubscriptionId=stripe_subscription_id,
        )
        print("usercreate")

        print (' just subscribed.')

    return HttpResponse(status=200)

my_venv/myproject/payment/templates/payment_cancel.html
{% extends 'base.html' %}
{% load static %}

{% block title %}あべろぐ | 有料会員登録{% endblock %}

{% block head %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}


{% block contents %}
<div class="a_detail">
    <div class="store-h1">
        <h1>有料会員登録</h1>
    </div>
    <hr class="hr1 mb-5">

    <div class="row justify-content-center">

        <div class="col-md-6">
            <h1>購入がキャンセルされました</h1>
            <div style="margin-top: 50px;">
            <u><a href="{% url 'gourmet:top' %}">トップページにもどる</a></u>
            </div>
        </div>
    </div>
</div>

{% endblock %}

my_venv/myproject/payment/templates/payment_checkout.html
{% extends 'base.html' %}
{% load static %}

{% block title %}あべろぐ | *******{% endblock %}
{% block head %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}

{% block contents %}
<section style="margin-left:500px;">
    <div class="product">
      <div class="description">
        <h3 class="fs-5">skilla t-shirt</h3>
        <h5>2,000円</h5>
      </div>
    </div>
    <button type="button" id="checkout-button">Checkout</button>
</section>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("pk_test_51Q11x3RwNoxwqPY3pyrduFZJqFQ829E73chC8IBdpDiUfoo5wEYbzjudV9g64kd2LOLVCmWVFUx94sE2IAm14xnT00Pu1xacZK");
    var checkoutButton = document.getElementById("checkout-button");
 
    checkoutButton.addEventListener("click", function () {
      fetch("/payment/create_checkout_session/", {
        method: "POST", 
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json; charset=UTF-8',
            'X-CSRFToken': '{{ csrf_token }}'
        },
      })

 
        .then(function (response) {
            console.log("check",response)
          return response.json(); /*jason形式でバックエンドから送られてきたデータをjavascriptのオブジェクト型に変換*/
        })
        .then(function (session) {
            console.log("check3",session)
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
            console.log("check4",result)
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });
</script>
{% endblock %}

my_venv/myproject/payment/templates/payment_index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}あべろぐ | 有料会員登録{% endblock %}

{% block head %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}


{% block contents %}
<div class="a_detail">
    <div class="store-h1">
        <h1>有料会員登録</h1>
    </div>
    <hr class="hr1 mb-5">

    <div class="row justify-content-center">

        <div class="col-md-6">
           <p style="color: red;">テストカード番号<br>
            4242 4242 4242 4242</p>
            <button class="mt-4 btn btn-danger" type="button" id="checkout-button">有料会員登録を行う</button>
            {% if subscription.status == "active" %}
            <p>あなたは有料会員登録済みです</p>
            {% else %}
            <p>有料会員ではない{{payment.status}}</p>
            {% endif %}
        </div>
    </div>
</div>

<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe("pk_test_51Q11x3RwNoxwqPY3pyrduFZJqFQ829E73chC8IBdpDiUfoo5wEYbzjudV9g64kd2LOLVCmWVFUx94sE2IAm14xnT00Pu1xacZK");
    var checkoutButton = document.getElementById("checkout-button");
 
    checkoutButton.addEventListener("click", function () {
      fetch("/payment/create_checkout_session/", { /*payment/が必要。第一引数は送信先のURL*/
        method: "POST",  /*今回はページ内に個人情報含まれていないのでGETメソッドでもいいが念の為ポストで送信*/
        headers: {
            'Accept': 'application/json',
            'Content-Type': 'application/json; charset=UTF-8',
            'X-CSRFToken': '{{ csrf_token }}'
        },
      })

        .then(function (response) {
            return response.json(); /*jason形式でバックエンドから送られてきたデータをjavascriptのオブジェクト型に変換*/
        })
        .then(function (session) {
            console.log("check3",session)
          return stripe.redirectToCheckout({ sessionId: session.id });
        })
        .then(function (result) {
            console.log("check4",result)
          // If redirectToCheckout fails due to a browser or network
          // error, you should display the localized error message to your
          // customer using error.message.
          if (result.error) {
            alert(result.error.message);
          }
        })
        .catch(function (error) {
          console.error("Error:", error);
        });
    });
</script>


{% endblock %}

my_venv/myproject/payment/templates/payment_success.html
{% extends 'base.html' %}
{% load static %}

{% block title %}あべろぐ | 有料会員登録{% endblock %}

{% block head %}
<script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
<script src="https://js.stripe.com/v3/"></script>
{% endblock %}


{% block contents %}
<div class="a_detail">
    <div class="store-h1">
        <h1>有料会員登録</h1>
    </div>
    <hr class="hr1 mb-5">

    <div class="row justify-content-center">

        <div class="col-md-6">
            <h1>購入ありがとうございます！</h1>
            <div style="margin-top: 50px;">
            <u><a href="{% url 'gourmet:top' %}">トップページにもどる</a></u>
            </div>
        </div>
    </div>
</div>

{% endblock %}