my_venv/myproject/gourmet/urls.py
from django.urls import path
from . import views


app_name = 'gourmet'
urlpatterns = [
    path('',views.TopView.as_view(), name='top'),
    path('detail/<int:pk>',views.StoreDetailView.as_view(),name='detail'),
    path('profile/',views.ProFileView.as_view(),name='profile'),
    path('profile-update/<int:pk>',views.ProfileUpdateView.as_view(),name='profile_update'),
    path('reservation-mail/',views.ReservationMail.as_view(),name='reservation_mail'),
    path('reservation-success/<int:reservation_id>', views.reservation_success, name='reservation_success'),
    path('reserve-list/',views.ReserveListView.as_view(), name='reserve_list'),
    path('reserve-delete/<int:pk>',views.ReserveDeleteView.as_view(),name='reserve_delete'),
    path('review/<int:store_id>/',views.submit_review,name='review_form'),
    path('review-edit/<int:pk>/',views.ReviewUpdateView.as_view(),name='review_edit'),
    path('review-delete/<int:pk>/',views.ReviewDeleteView.as_view(),name='review_delete'),
    path('confirm/',views.ConfirmReservation.as_view(),name='confirm'),
    path('like/<int:store_id>',views.toggle_favorite,name='toggle_favorite'), #like_rest(同期処理)からtoggle_favoriteb (非同期処理)に変更
    path('like-list/',views.LikeListView.as_view(),name='like_list'),
    path('toggle-fav/<int:store_id>/', views.toggle_fav,name ='toggle-fav'),
    path('search/',views.SearchResultView.as_view(),name='search'),
    path('member/',views.MemberShipView.as_view(),name='membership'),
    path('only-member/',views.MemberPageView.as_view(),name='membership_page'),
    path('member-update/<int:pk>/',views.MemberUpdateView.as_view(),name='membership_edit'),
    path('membership-delete/<int:pk>/',views.MembershipDeleteView.as_view(),name='membership_delete'),
    path('mypage/',views.MypageListView.as_view(),name='mypage'),
    path('mypage-form/',views.MyPageFormView.as_view(),name='mypage_form'),
    path('mypage-edit/<int:pk>',views.MypageUpdateView.as_view(),name='mypage_edit'),
    path('mypage-delete/<int:pk>',views.MypageDeleteView.as_view(),name='mypage_delete'),
    path('ourpage/',views.OurpageListView.as_view(),name='ourpage'),
    path('want-list/',views.WantView.as_view(),name='want_list'),
    path('want-list-form/',views.WantFormView.as_view(),name='want_list_form'),
    path('want-list-edit/<int:pk>/',views.WantUpdateView.as_view(),name='want_edit'),
    path('want-list-delete/<int:pk>/',views.WantDeleteView.as_view(),name='want_delete'),
]

my_venv/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import static
from .import settings
from . import settings_common, settings_dev


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gourmet.urls')),
    path('accounts/',include('allauth.urls')),
    path('payment/',include('payment.urls'),)
]

#開発サーバーでメディアを配信できるようにする設定

urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

my_venv/myproject/gourmet/models.py
from django.db import models
from django.db.models import UniqueConstraint
from accounts.models import CustomUser
from django.core.validators import RegexValidator
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import redirect
from django.utils import timezone

CustomUser = get_user_model()

import datetime

# カテゴリ分類(Productクラスより上で定義する必要がある。)
class Category(models.Model):
    # categoryはプルダウン式のため、選択肢を記載(管理画面からはカテゴリを新規登録できない仕様にしている。)

    category_choices = [
    ('和食', '和食'),
    ('中華', '中華'),
    ('イタリアン', 'イタリアン'),
    ('フレンチ', 'フレンチ'),
    ('寿司','寿司'),
    ('焼肉','焼肉'),
    ('韓国料理','韓国料理'),
    ('タイ料理','タイ料理'),
    ('スペイン料理','スペイン料理'),
    ('海鮮','海鮮'),
    ('洋食','洋食'),
    ('バー','バー'),
    ('ハンバーガー','ハンバーガー'),
    ('スイーツ','スイーツ'),
    ('カレー','カレー'),
    ('鉄板焼き/お好み','鉄板焼き/お好み'),
    ('ラーメン','ラーメン'),
    ('ベーカリー','ベーカリー'),
    ('串/揚げ物','串/揚げ物'),
    ('カフェ','カフェ'),
    ('その他','その他')
]

    category = models.CharField(verbose_name='ジャンル', choices=category_choices, max_length=50,null=True,blank=True)
    
    def __str__(self):
        return dict(self.category_choices)[self.category]

#店舗詳細
class StoreInfo(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT)
    store_name = models.CharField(verbose_name='店舗名',max_length=40)
    #カテゴリーはForeignKey
    category = models.ForeignKey(Category,verbose_name='ジャンル',on_delete=models.CASCADE)
    store_detail = models.TextField(verbose_name='店舗詳細',blank=True, null=True)
    store_address = models.TextField(verbose_name='店舗住所',blank=True,null=True)
    store_email = models.EmailField(verbose_name='店舗メールアドレス',blank=True,null=True)
    store_phone_number = models.CharField(verbose_name='店舗電話番号',max_length=13, blank=True,null=True)
    photo1 = models.ImageField(verbose_name='写真1',blank=True,default='noImage.png')
    photo2 = models.ImageField(verbose_name='写真2',blank=True,default='noImage.png')
    photo3 = models.ImageField(verbose_name='写真3',blank=True,default='noImage.png')
    create_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)

     # 圧縮フィールドを追加
    photo1_compressed = models.ImageField(blank=True, null=True)
    photo2_compressed = models.ImageField(blank=True, null=True)
    photo3_compressed = models.ImageField(blank=True, null=True)

    #定休日追加
    holiday_choices = [
    ('月' ,'月'),
    ('火','火'),
    ('水','水'),
    ('木','木'),
    ('金','金'),
    ('土','土'),
    ('日','日'),
    ('不定休','不定休'),
    ('なし','なし'),
    ('臨時休業','臨時休業')
    ]
    holiday = models.CharField(verbose_name='定休日1',choices=holiday_choices,max_length=10,blank=True,null=True)
    holiday2 = models.CharField(verbose_name='定休日2',choices=holiday_choices,max_length=10,blank=True,null=True)
    holiday3 = models.CharField(verbose_name='定休日3',choices=holiday_choices,max_length=10,blank=True,null=True)


    #不定休の場合は備考記載
    irregular = models.CharField(verbose_name='不定休の場合は備考を記入してください。',max_length=200,blank=True,null=True)

    


    class Meta:
        verbose_name_plural = 'StoreInfo'

    def __str__(self):
        return self.store_name
    
#予約情報
class Reservation(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT)
    store_name = models.ForeignKey(StoreInfo, verbose_name='店名',on_delete=models.PROTECT)
    date = models.DateField(verbose_name='予約日')
    time = models.TimeField(verbose_name='予約時間')
    persons = models.IntegerField(verbose_name='予約人数')
    is_visible = models.BooleanField(verbose_name='来店済み',default=False) #予約完了=True

#レビュー
class Review(models.Model):
    score = models.PositiveIntegerField(blank=False, default=1)
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.CASCADE, null=True)
    store_name = models.ForeignKey(StoreInfo, verbose_name='店名',on_delete=models.PROTECT)
    handle = models.CharField(verbose_name='ニックネーム',max_length=50)
    title = models.CharField(verbose_name='タイトル',max_length=50)
    content = models.TextField(verbose_name='レビュー内容')
    create_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)
    review_photo1 = models.ImageField(verbose_name='レビュー写真1',upload_to='reviews/',blank=True)
    review_photo2 = models.ImageField(verbose_name='レビュー写真2',upload_to='reviews/',blank=True)
    review_photo3 = models.ImageField(verbose_name='レビュー写真3',upload_to='reviews/',blank=True)

    #圧縮フィールドを追加
    photo1_compressed = models.ImageField(blank=True, null=True)
    photo2_compressed = models.ImageField(blank=True, null=True)
    photo3_compressed = models.ImageField(blank=True, null=True)


    def __str__(self):
        return self.user.username
    
#お気に入り機能
class Like(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.PROTECT)
    fav = models.ForeignKey(StoreInfo, verbose_name='お気に入り店舗', on_delete=models.CASCADE) #StoreInfoクラスの各インスタンスを識別するための変数
    create_at = models.DateTimeField(auto_now_add=True)

    #userとfavの組み合わせが一意=同じユーザーが同じレビューに対して複数回いいねすることができないようにDBレベルで制約をつける。
    class Meta:
        constraints = [
            UniqueConstraint(fields=['user','fav'], name='unique_user_fav')
        ]
    def __str__(self):
        return f"{self.user.username}が{self.fav.store_name}をいいねしました"
        # return self.fav.store_name

#有料会員リスト

#クレジットカード番号を14~16桁に制限する正規表現
card_regex = RegexValidator(
    regex=r'^\d{14,16}$',  # 7桁の数字のみを許容する正規表現
    message="カード情報が正しくありません。",
)

#大文字のみを許可する正規表現
char_regex = RegexValidator(
    regex = r'^[A-Z\s]+$', #大文字とスペースは許可 
    message="大文字のアルファベットを入力してください。",
)

#カードブランドは追加・削除を容易にするため別で定義
class CardBrand(models.Model):
    name = models.CharField(verbose_name='カードブランド', max_length=50, unique=True)

    def __str__(self):
        return self.name

class Member(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.CASCADE, null=False) #ユーザー情報から削除されたらこちらからも削除
    card_brand = models.ForeignKey(CardBrand, on_delete=models.CASCADE)
    last4 = models.CharField(validators=[card_regex],max_length=16) #IntengerFieldを使うと0123が123として保存されてしまうため、文字列として保存してエラーを回避

    MONTH_CHOICES = [('','月')]+[(i, str(i).zfill(2)) for i in range(1, 13)] #zfillで文字列として1桁の数字を0埋め(1,'01')として格納
    exp_month = models.PositiveIntegerField(verbose_name='月',choices=MONTH_CHOICES)

    CURRENT_YEAR = datetime.datetime.now().year
    YEAR_CHOICES = [('','年')]+[(i, str(i)) for i in range(CURRENT_YEAR, CURRENT_YEAR + 20)] #今から20年後までを選択肢として追加
    exp_year = models.PositiveBigIntegerField(verbose_name='年',choices=YEAR_CHOICES)

    cardholder = models.CharField(validators=[char_regex], verbose_name='カード名義',max_length=50,null=True)

    #同じユーザー名で登録を重複しないように制約をつける(複数カード登録も不可)
    class Meta:
        constraints = [
            UniqueConstraint(fields=['user'],name='unique_user_member')
        ]

    def __str__(self):
        return f"{self.user.full_name}さんが有料会員にプランを変更しました。"
    
#マイページ(他ログ)
class Mypage(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.CASCADE)
    store_name = models.CharField(verbose_name='お店の名前',max_length=40)
    #カテゴリーはForeignKey
    category = models.ForeignKey(Category,verbose_name='ジャンル',on_delete=models.CASCADE)
    store_address = models.CharField(verbose_name='お店の場所',max_length=40,blank=True,null=True)
    feeling = models.TextField(verbose_name='お店の感想',max_length=70,blank=True,null=True)
    photo1 = models.ImageField(verbose_name='写真1(必須)')
    photo2 = models.ImageField(verbose_name='写真2',blank=True)
    photo3 = models.ImageField(verbose_name='写真3',blank=True)
    create_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)

     # 圧縮フィールドを追加
    photo1_mycompressed = models.ImageField(blank=True, null=True)
    photo2_mycompressed = models.ImageField(blank=True, null=True)
    photo3_mycompressed = models.ImageField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'マイページ'

    def __str__(self):
        return self.store_name

#行きたいとこリスト
class WantPlace(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー',on_delete=models.CASCADE)
    store_name = models.CharField(verbose_name='行きたいお店',max_length=40)
    web_site = models.URLField(verbose_name='お店のURL',blank=True)
    comment = models.CharField(verbose_name='一言コメント',blank=True,max_length=100)
    visited = models.BooleanField(verbose_name='行った！', default=False)  # 行ったかどうか
    revisit = models.BooleanField(verbose_name='リピあり！', default=False)  # リピートしたいかどうか
    create_at = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時',auto_now=True)

    class Meta:
        verbose_name_plural = '行きたいとこリスト'

    def __str__(self):
        return self.store_name

#stripe決済で有料会員かどうかを判定するモデル
class Stripe_Customer(models.Model):
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE)
    stripeCustomerId = models.CharField(verbose_name='stipe顧客ID', max_length=255)
    stripeSubscriptionId = models.CharField(verbose_name='stripeサブスクID', max_length=255)
    regist_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = 'stripeサブスク会員'

    def __str__(self):
        return self.user.username

my_venv/myproject/gourmet/forms.py
from django import forms
from django.forms import PasswordInput  

from  accounts.models import CustomUser #accounts.models.pyのクラスを継承する。
from .models import Reservation,Review,Member,Mypage,WantPlace

#ユーザー情報
class ProfileForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('full_name','furigana','handle','email','postal_code','address','phone_number') #accounts/models.pyのフィールドのデータを参照

    #全フォームフィールドに一括でBootstrapのform-controlクラスを追加できる。
    def __init__(self,*args,**kwargs):  
        super().__init__(*args,**kwargs)
        for field in self.fields.values(): #selfはインスタンス化されたクラス自身
            field.widget.attrs['class'] = 'form-control' 


#予約フォーム
class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['date', 'time', 'persons']
        widgets = {
            'date': forms.TextInput(attrs={'class': 'form-control fieldset__input js__datepicker mb-3', 'placeholder': '予約の日付を選択してください。'}),
            'time': forms.TextInput(attrs={'class': 'form-control fieldset__input js__timepicker mb-3', 'placeholder': '予約の時間を選択してください。'}),
            'persons': forms.Select(attrs={'class': 'form-control mb-3'}, choices=[
                ('', '予約人数を選択してください'),
                (1, '1名'),
                (2, '2名'),
                (3, '3名'),
                (4, '4名'),
                (5, '5名以上')
            ])
        }

#レビューフォーム
class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score','handle','title','content','review_photo1','review_photo2','review_photo3']
    def __init__(self,*args,**kwargs):  
        super().__init__(*args,**kwargs)
        self.fields['handle'].widget.attrs['class']='form-control'
        self.fields['handle'].widget.attrs['style']='text-align:left'
        self.fields['handle'].widget.attrs['placeholder']='ニックネームを入力してください。' #読み取り専用、入力不可に
        self.fields['handle'].widget.attrs['readonly']='readonly' #読み取り専用、入力不可に
        self.fields['title'].widget.attrs['class']='form-control'
        self.fields['title'].widget.attrs['style']='text-align:left'
        self.fields['title'].widget.attrs['placeholder']='タイトルを入力してください。'
        self.fields['content'].widget.attrs['class']='form-control'
        self.fields['content'].widget.attrs['style']='text-align:left'
        self.fields['content'].widget.attrs['placeholder']='口コミの内容を入力してください。'
        self.fields['review_photo1'].widget.attrs['class']='form-control'
        self.fields['review_photo2'].widget.attrs['class']='form-control'
        self.fields['review_photo3'].widget.attrs['class']='form-control'


#有料会員登録
class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['card_brand','last4','exp_month','exp_year','cardholder']

    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        #下に更新されていってしまうのでこの順番は変えない。
        self.fields['card_brand'].widget.attrs['placeholder']='クレジットカードの種類を選択してください。'
        self.fields['last4'].widget = PasswordInput(attrs={'placeholder': '1234 1234 1234 1234'})
        self.fields['cardholder'].widget.attrs['placeholder']='WAKAMARU SAKAGUCHI'

        for field in self.fields.values(): #selfはインスタンス化されたクラス自身
            field.widget.attrs['class'] = 'form-control' 
            field.widget.attrs['style'] = 'text-align:left'
        
        self.fields['exp_month'].widget.attrs['style']='width:50px;'
        self.fields['exp_year'].widget.attrs['style']='width:75px;'

#マイページ(他ログ)
class MypageForm(forms.ModelForm):
    class Meta:
        model = Mypage
        fields = ['store_name','category','store_address','feeling','photo1','photo2','photo3']

         #全フォームフィールドに一括でBootstrapのform-controlクラスを追加できる。
    def __init__(self,*args,**kwargs):  
        super().__init__(*args,**kwargs)
        for field in self.fields.values(): #selfはインスタンス化されたクラス自身
            field.widget.attrs['class'] = 'form-control' 
            field.widget.attrs['style']='text-align:left'
        self.fields['feeling'].widget.attrs['placeholder']='最大70文字'

#行きたいとこリストフォーム
class WantPlaceForm(forms.ModelForm):
    class Meta:
        model = WantPlace
        fields = ['store_name','web_site','comment']

    def __init__(self,*args,**kwargs):  
        super().__init__(*args,**kwargs)
        for field in self.fields.values(): #selfはインスタンス化されたクラス自身
            field.widget.attrs['class'] = 'form-control' 
            field.widget.attrs['style']='text-align:left'

my_venv/myproject/gourmet/templates/membership_page.html
{% extends 'base.html' %}
{% load static %}

{% block title %}あべろぐ | 有料会員限定{% endblock %}

{% block contents %}
<div class="a_detail">
    <div class="store-h1">
        <h1>有料会員限定ページ</h1>
    </div>
    <hr class="hr1 mb-5">

    <div class="row justify-content-center">

        <div class="col-md-6">
            <div>
                <p>こちらは会員限定のページです。<br>月額300円で会員限定機能が使い放題!</p>
                <br>
                <a  class="member-edit" href="{% url 'gourmet:membership_edit' member.pk %}">会員情報を変更する</a>
            </div>
        </div>
    </div>
</div>
<a style="position: absolute; top: 20px; right: 30px;" href="{% url 'gourmet:membership_delete' member.pk %}">解約する</a>


{% endblock %}

my_venv/myproject/gourmet/templates/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}あべろぐ | ほかろぐ{% endblock %}
{% block active-effe3 %}active{% endblock %}


{% block contents %}
<style>
@media (max-width: 767px) {
    main {
        height: 3550px; /* 必要に応じて高さを調整 */
    }
}


/* Swiper コンテナのスタイル */
.swiper-container {
    position: relative; /* 親要素としての相対位置 */
    height: 180px; /* 画像の高さに合わせて調整 */
    overflow: hidden; /* スライドがコンテナを超えないようにする */
}

/* スライド内の画像のサイズ調整 */
.swiper-slide {
    width: 100%; /* 各スライドの幅をコンテナに合わせる */
    height: 100%; /* 各スライドの高さをコンテナに合わせる */
}

/* スライド内の画像のサイズ調整 */
.swiper-slide img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    object-fit: cover;
    object-position: center;
}

/* ナビゲーションボタンのスタイル */
.swiper-button-next, .swiper-button-prev {
    position: absolute; /* 親要素内での絶対位置指定 */
    top: 50%; /* 親要素の高さの中央に配置 */
    transform: translateY(-50%); /* 縦方向の中央揃え */
    color: #fff; /* ボタンの色 */
    background: rgba(0, 0, 0, 0.5); /* ボタンの背景色 */
    border-radius: 50%;
    width: 30px;
    height: 30px;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 10; /* ボタンを画像の上に表示 */
}

/* 右側のナビゲーションボタン */
.swiper-button-next {
    right: 10px; /* 右端からの距離 */
}

/* 左側のナビゲーションボタン */
.swiper-button-prev {
    left: 10px; /* 左端からの距離 */
}

/* ページネーションのスタイル */
.swiper-pagination-bullet {
    background: rgba(255, 255, 255, 0.5); /* デフォルトの点の色（白の半透明） */
}

/* アクティブなバレットのスタイル */
.swiper-pagination-bullet-active {
    background: #fff !important; /* アクティブな点の色（白） */
}

.swiper-pagination {
    position: absolute;
    bottom: 10px; /* ページネーションを下部に配置 */
    left: 50%; /* 中央に配置 */
    transform: translateX(-50%); /* 水平方向で中央揃え */
    z-index: 15; /* 画像より上に表示 */
    display: flex;
    justify-content: center; /* 中央揃え */
}



</style>

<!-- Swiper JS の初期化 -->
<script>
document.addEventListener('DOMContentLoaded', function () {
    var swiper = new Swiper('.swiper-container', {
        slidesPerView: 1,
        spaceBetween: 10,
        pagination: {
        el: '.swiper-pagination',
        clickable: true,
        bulletActiveClass: 'swiper-pagination-bullet-active',
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev',
        },
    });
});

</script>






<div class="a_detail">
    <div class="store-h1">
        <h1>ほかろぐ</h1>
    </div>
    <hr class="hr1 mb-5">
    <div class="d-flex justify-content-end">
        <a href="{% url 'gourmet:mypage_form' %}" class="btn btn-lg hoka-btn" >+</a>
    </div>
    <a href="{% url 'gourmet:ourpage' %}" style="display: block; text-align: left; margin: 30px 0; font-size: 20px !important;"><u>みんろぐページへ</u></a>

    <div class="container">
        <div class="row row-cols-1 row-cols-md-3 g-5">
            {% for mypage in mypages %}
            <div class="col mb-5">
                <div class="card" style="height: 450px !important; display: flex; flex-direction: column;">
                    <div class="swiper-container">
                        <div class="swiper-wrapper">
                            {% if mypage.photo1 %}
                            <div class="swiper-slide">
                                {% if mypage.photo1_mycompressed %}
                                <img src="{{ mypage.photo1_mycompressed.url }}" class="card-img-top">
                                {% else %}
                                <img src="{{ mypage.photo1.url }}" class="card-img-top">
                                {% endif %}
                            </div>
                            {% endif %}
                            {% if mypage.photo2 %}
                            <div class="swiper-slide">
                                {% if mypage.photo2_mycompressed %}
                                <img src="{{ mypage.photo2_mycompressed.url }}" class="card-img-top">
                                {% else %}
                                <img src="{{ mypage.photo2.url }}" class="card-img-top">
                                {% endif %}
                            </div>
                            {% endif %}
                            {% if mypage.photo3 %}
                            <div class="swiper-slide">
                                {% if mypage.photo3_mycompressed %}
                                <img src="{{ mypage.photo3_mycompressed.url }}" class="card-img-top">
                                {% else %}
                                <img src="{{ mypage.photo3.url }}" class="card-img-top">
                                {% endif %}
                            </div>
                            {% endif %}
                        </div>
                        <!-- Add Pagination -->
                        <div class="swiper-pagination"></div>
                        <!-- Add Navigation -->
                        <div class="swiper-button-next"></div>
                        <div class="swiper-button-prev"></div>
                    </div>

                    <div class="card-body d-flex flex-column text-start" style="flex: 1;">
                        <p class="text-end">{{mypage.create_at}}</p>
                        <p class="text-end mb-2" style="font-style: italic;">{{mypage.user}}</p>
                        <h5 class="card-title"><strong>{{ mypage.store_name }}</strong></h5>
                        <p class="card-text" style="padding-left: 0; margin-bottom: 20px;">{{ mypage.feeling }}</p>
                        <div style="margin-top: auto;">
                            <p><i class="fa-solid fa-location-dot"></i>{{ mypage.store_address }}</p>
                            <p>#{{ mypage.category }}</p>
                        </div>
                    </div>
                </div>
                <div class="d-flex justify-content-end">
                <a href="{% url 'gourmet:mypage_edit' pk=mypage.pk %}" style="margin-right: 15px;"><u>編集</u></a>
                <a href="{% url 'gourmet:mypage_delete' pk=mypage.pk %}" style="margin-right: 10px;"><u>削除</u></a>
                </div>
            </div>
            {% empty %}
            <p class="mt-5">レビューはありません。</p>
            {% endfor %}
        </div>
    </div>

    <ul class="Pagination">
        {% if page_obj.has_previous %}
        <li class="Pagination-Item">
            <a class="Pagination-Item-Link" href="?page={{ page_obj.previous_page_number }}">
                <svg xmlns="http://www.w3.org/2000/svg" class="Pagination-Item-Link-Icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M11 19l-7-7 7-7m8 14l-7-7 7-7" />
                </svg>
            </a>
        </li>
        {% endif %}
        {% for num in page_obj.paginator.page_range %}
        <li class="Pagination-Item">
            <a class="Pagination-Item-Link {% if page_obj.number == num %}isActive{% endif %}" href="?page={{ num }}"><span>{{ num }}</span></a>
        </li>
        {% endfor %}
        {% if page_obj.has_next %}
        <li class="Pagination-Item">
            <a class="Pagination-Item-Link" href="?page={{ page_obj.next_page_number }}">
                <svg xmlns="http://www.w3.org/2000/svg" class="Pagination-Item-Link-Icon" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M13 5l7 7-7 7M5 5l7 7-7 7" />
                </svg>
            </a>
        </li>
        {% endif %}
    </ul>  

{% endblock %}